/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Application {
  description?: string;
  name: string;
  outputDirectory: string;
  title: string;
  version?: string;
}
